### ISSUE TITLE
Reply : clone canmv repositories was unsuccessful.

### ISSUE THREAD

**Issue by QiaoTuCodes** [kendryte/canmv#1]
why clone canmv repositories be block up in  https://git.savannah.gnu.org/r/lwip.git submodule relpy say: 
```TypeScript
Cloning into 'lib/lwip'...
fatal: unable to access 'https://git.savannah.gnu.org/r/lwip.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
fatal: clone of 'https://git.savannah.gnu.org/r/lwip.git' into submodule path 'lib/lwip' failed
Failed to recurse into submodule path 'components/micropython/core'
root@iZj6c41val1n077ywxww8iZ:~#
```
this probem like about certificates ? what happend ?

**Comment by kendryte747** [comment]
https://github.com/kendryte/canmv/actions/runs/3345737389/jobs/5541643396#step:3:436
In github actions, can clone this submodule, try use `git submodule update --init --recursive` in canmv top level folder.

**Comment by QiaoTuCodes** [comment]
i try used:
```shell
 git clone -b v1.0.4 --recursive https://github.com/kendryte/canmv.git 
```
also can't gain it.

**Comment by QiaoTuCodes** [comment]
It seems to be a SSL permission problem. and i try edit the submodule configure files , redirect link to old https link that download successful. note: old link from micropython ver 1.9 submodule.

**Comment by kendryte747** [comment]
![image](https://user-images.githubusercontent.com/116556725/199378450-510660ba-a196-48e7-8916-1dac4e7cbf60.png)
it seems you should have a good network without GFW.

this submodule is not necessary, so you can skip this error.

**Comment by QiaoTuCodes** [comment]
okey i know how do i do that. so thank you very much! :)

**Comment by kendryte747** [comment]
This issue will be closed because it has not had recent activity.
Thank you for your contributions.
