### ISSUE TITLE
How to use ram_nocache memory in kendryte.ld file 

### ISSUE THREAD

**Issue by nbenhur** [kendryte/canmv#13]
In the project canmv_k210 there is kendryte.ld linker script. In that ram_nocache is initialized in Memory region. But it is nowhere used in the other part of the linker script. I need clarity on the following below points regarding ram_nocache.
1. What is the use of ram_nocache?
2. What is the size of ram_nocache and is it available separately as physical memory along with ram or it is a mirror of ram memory?
3. Can i use ram_nocache as general purpose ram and extend ram memory?, if so, how to do it? 

**Please complete the following information**
 - IDE version: V1.0.4
 - Firmware version: v1.0.4
 - Board: maix-bit-mic
 - OS: Linux - Ubuntu 20.04

**Comment by kendryte747** [comment]
ram_nocache is a mirror of ram, you can not use it as general purpose ram.

**Comment by kendryte747** [comment]
I'm closing this question due to a long period of inactivity, feel free to reopen this question if you have any questions.
