### ISSUE TITLE
bug or other?

### ISSUE THREAD

**Issue by QiaoTuCodes** [kendryte/canmv#16]
We can't useing the Native code emitter & Viper code emitter on canmv boards! why?

a sample here:
```python
@micropython.viper
def foo(self, arg: int) -> int:
    # code
```

```python
@micropython.native
def foo(self, arg: int) -> int:
    # code
```
We are test out any mpy-boards it's support this method in all micropython versions of anyway. but seem can not to be useing on the K210 chips? i don't know why?  can you explain that? Thanks anyway!

**Comment by starstar222** [comment]
At present, micropython has not adapted the risc-v chip

**Comment by QiaoTuCodes** [comment]
got it! . ok Thank you.
