### ISSUE TITLE
LCD

### ISSUE THREAD

**Issue by weilian1977** [kendryte/canmv#20]
there （https://github.com/kendryte/canmv/tree/main/components/drivers/lcd)/src/） give MCU and RGB driver，Can give some LCD Specific model that MCU and RGB driver support？

**Comment by starstar222** [comment]
The default lcd uses ST7789 driver ic, and has 8080 interface. K210 does not support rgb LCD, it is not recommended.

**Comment by weilian1977** [comment]
Thanks a lot，K210 8080 interface  can supported How high resolution？480*320？

**Comment by kendryte747** [comment]
The resolution is limited by memory and lcd controller. K210 use spi simulate 8080, output speed up to 120Mhz.

**Comment by weilian1977** [comment]
how about 800*480？

**Comment by kendryte747** [comment]
Our customer has driven 800x480 MCU screen~

**Comment by weilian1977** [comment]
8080？or need other chip？

**Comment by kendryte747** [comment]
8080
