### ISSUE TITLE
jpeg encode and decode

### ISSUE THREAD

**Issue by weilian1977** [kendryte/canmv#26]
K210 chip support hardware jpeg encode and decode？

**Comment by kendryte747** [comment]
K210 have no hardware jpeg codec.

**Comment by weilian1977** [comment]
software jpeg encode and decode？encode and decode speed？

**Comment by kendryte747** [comment]
Use [stb_image](https://github.com/nothings/stb/blob/master/stb_image.h) decode this jpeg 
![t](https://user-images.githubusercontent.com/116556725/227418700-6ffdcb76-ec3a-413d-bbe7-3fe198bdf348.jpeg) used 29914 us.

Use [stb_image_write](https://github.com/nothings/stb/blob/master/stb_image_write.h) encode camera image such as this jpeg 
![img_5119](https://user-images.githubusercontent.com/116556725/227418939-ae8a0387-90a2-4aea-b67f-93add7becb74.jpg) used 42481 us.(quality is 90)

CPU Freq is 400Mhz.
