### ISSUE TITLE
Multiple Outputs

### ISSUE THREAD

**Issue by BillisC** [kendryte/canmv#27]
How can I get mutiple outputs from my models? Because it returns me only the first output. I remember maixpy allowed me to setup each output individually but I can't find anything similar in canmv.

**Comment by kendryte747** [comment]
Now we have add support for this in the feat/kpu branch,
you can refer this commit #28, and download the prerelease firmware from [github actions](https://github.com/kendryte/canmv/actions/runs/4339568525)
with the document for this [here](https://kendryte.github.io/canmv_docs/main/canmv/library/canmv/maix/maix.KPU_NEW.html#get-outputs),and the new examples [here](https://github.com/kendryte/canmv_examples/tree/main/98-KPU_NEW)

**Comment by BillisC** [comment]
thank you, I would also like to know if there are plans to merge kmodel v5. Otherwise is there any other way to run my v5 models?

**Comment by kendryte747** [comment]
We have a plan to support kmodel v5, will be ready at the end of March.

**Comment by BillisC** [comment]
ok thank you
