### ISSUE TITLE
Details on the releases

### ISSUE THREAD

**Issue by beckmx** [kendryte/canmv#33]
hello guys, I was just wondering what features does every release has, I can see some specifics for the k210, what is the difference between the lite and the rest? can you also give details on the memory left available?, just to have an idea which to pick

**Comment by kendryte747** [comment]
![image](https://user-images.githubusercontent.com/116556725/229276454-2de5ef43-2c04-4511-8232-a2825651ee7f.png)
Such as k210, canmv_k210_standard.bin use [config_standard.mk](https://github.com/kendryte/canmv/blob/main/projects/canmv_k210/config_standard.mk), canmv_k210_lite.bin use [config_lite.mk](https://github.com/kendryte/canmv/blob/main/projects/canmv_k210/config_lite.mk), if you want run a big kmodel, you can use canmv_k210_lite.bin, it disabled some functions to more memory for run kmodel

**Comment by beckmx** [comment]
Both options can be seen in the mv ide?

**Comment by kendryte747** [comment]
> Both options can be seen in the mv ide?

No

**Comment by starstar222** [comment]
> hello guys, I was just wondering what features does every release has, I can see some specifics for the k210, what is the difference between the lite and the rest? can you also give details on the memory left available?, just to have an idea which to pick

Please refer to the document description：[projects/README.md](https://github.com/kendryte/canmv/blob/main/projects/README.md)
