### ISSUE TITLE
SYSCALL: Out of memory when loading v5 model

### ISSUE THREAD

**Issue by BillisC** [kendryte/canmv#34]
**Describe the bug**
Using **feat/kpu** branch, I tried loading my squeezenet model (quantized & kmodel v5) but the results were:
```
Probe model size failed, will skip size check.                                                    
E (791017052) SYSCALL: Out of memory                                                              
                                                                                                  
Traceback (most recent call last):                                                                
  File "boot.py", line 13, in <module>                                                            
OSError: Failed to load model
```
I should note that the firmware is very minimal and I've replaced nncase runtime v1.1 with v1.8 to match my model's compiler.
I attached the files in the zip: [files.zip](https://github.com/kendryte/canmv/files/11261787/files.zip)

**Please complete the following information**
 - Firmware version: v1.0.5-5-ge1b2766-dirty (Customized)
 - Board: Sipeed Maixduino

**Comment by kendryte747** [comment]
The firmware is too big to run Kmodel v5, you can set Minimum size OMV function ON.
![image](https://user-images.githubusercontent.com/116556725/233239377-41d062c7-4bf4-45a5-b11e-a8dc4d1ce93b.png)

**Comment by BillisC** [comment]
Alright so I've managed to shrink firmware's size down to 1.6 MB, but the issue is still the same.
I even tried reducing GC heap size and free memory was like this:
```
Free GC Heap: 374KB                                                                                  
Free Heap: 3712KB 
```
It's pretty weird that the model cannot fit inside the memory. What else could cause this? The model originated from Pytorch and it was converted to ONNX (hence the need for KModel v5).

**Comment by BillisC** [comment]
I'm loading the model from my SD card if that helps

**Comment by kendryte747** [comment]
You can use older nncase runtime.

**Comment by BillisC** [comment]
Tried nncase v1.1 and still out of memory. Apparently I tried a custom lenet5 model with v5 and it worked by allocating only ~100kb. So could it be that the model input/output layers could trouble k210? It's squeezenet with 1000 classes output.

**Comment by kendryte747** [comment]
input and output layer will alloc some memory, maybe it cause the issuse.

**Comment by narduzzi** [comment]
Hi @BillisC, how did you replace the runtime of nncase? 
Did you had to change any file in this project? Is replacing the kmodel file sufficient?
